# Generated by Django 3.1.3 on 2020-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(max_length=10, verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('ponto_referencia', models.CharField(max_length=150, verbose_name='Ponto de Referêmcia')),
            ],
        ),
    ]
