# Generated by Django 3.1.3 on 2020-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientes',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosclientes',
            name='ponto_referencia',
            field=models.CharField(max_length=150, verbose_name='Ponto de Referência'),
        ),
    ]
