# Generated by Django 3.1.3 on 2020-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20201113_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientes',
            name='cidade',
            field=models.CharField(default='', max_length=150, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosclientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logradouro(rua)'),
        ),
        migrations.AlterField(
            model_name='dadosclientes',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
