# Generated by Django 3.1.3 on 2020-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20201114_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosclientes',
            old_name='endereco',
            new_name='logradouro',
        ),
        migrations.AlterField(
            model_name='dadosclientes',
            name='nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Completo'),
        ),
    ]
